matrix:
  include:
    - env: ver=2019-06-27T21-13-50Z
    - env: ver=2019-07-05T21-20-21Z
#    - env: ver=2019-07-10T00-34-56Z
#    - env: ver=2019-07-17T22-54-12Z
#    - env: ver=2019-07-24T02-02-23Z
#    - env: ver=2019-07-31T18-57-56Z
#    - env: ver=2019-08-01T22-18-54Z
#    - env: ver=2019-08-07T01-59-21Z
#    - env: ver=2019-08-14T20-37-41Z
#    - env: ver=2019-08-21T19-40-07Z
 
language: go

os: linux-ppc64le
dist: trusty
sudo: required
env: version=2019-06-01T03-46-14Z ARCH=ppc64le CGO_ENABLED=0 GO111MODULE=on

# Enable build cache
# https://restic.net/blog/2018-09-02/travis-build-cache
cache:
 directories:
   - $HOME/.cache/go-build
   - $HOME/gopath/pkg/mod
   - $HOME/go/pkg/mod

go: 1.12.1

before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [[ "${TRAVIS_OS_NAME}" == "linux-ppc64le" ]]; then sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'; fi

before_install:
 - sudo apt install -y lftp
 - if [[ "$TRAVIS_OS_NAME" == "linux-ppc64le" ]]; then nvm install node ; fi

script:
  - python3 ftp_version.py
  - bash build.sh
