language: go
os: linux-ppc64le
sudo: required
env: version=2019-06-01T03-46-14Z ARCH=ppc64le CGO_ENABLED=0 GO111MODULE=on

# Enable build cache
# https://restic.net/blog/2018-09-02/travis-build-cache
cache:
 directories:
   - $HOME/.cache/go-build
   - $HOME/gopath/pkg/mod
   - $HOME/go/pkg/mod

go: 1.12.x

before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [[ "${TRAVIS_OS_NAME}" == "linux-ppc64le" ]]; then sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'; fi

before_install:
 - sudo apt install -y lftp
 - if [[ "$TRAVIS_OS_NAME" == "linux-ppc64le" ]]; then nvm install node ; fi

script:
  - python3 ftp_version.py
  - bash build.sh
